# 2.3 Linear Algebra

In [14]:
import torch

## 2.3.1 Scalars
The expression $ x \in \R $ is a formal way to say that $x$ is a real-valued scalar.

$x,y \in \{0, 1\}$ indicates that $x$ and $y$ are variables that can only take values $0$ or $1$.

Scalars are implemented as tensors that contain only one element.

In [15]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2.3.2 Vectors
Vectors are implemented as 1st-order tensors. In general, such tensors can have arbitrary lengths. 

In [16]:
x = torch.arange(3)
x, len(x), x.shape

(tensor([0, 1, 2]), 3, torch.Size([3]))

$x_2$ denotes the second element of $\vec{x}$. It is a scalar.

To indicate that a vector contains $n$ elements, we write $x \in \R^n$. Formally, we call $n$ the dimensionality of the vector.

We use **order** to refer to the number of axes, and **dimensionality** exclusively to refer to the number of components.

## 2.3.3 Matrices
Just as scalars are 0th-order tensors and vectors are 1st-order tensors, matrices are 2nd-order tensors.

The expression $\vec{A} \in \R^{m \times n}$ indicates that matrix $\vec{A}$ contains $m \times n$ real-valued scalars.

In [17]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

To flip the axes of a matrix, we transpose it.

$$ B = A^T $$

If a square matrix is equal to its transpose, we call it **symmetric**.

In [18]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

## 2.3.4 Tensors
Tensors are nth-order arrays.

In [19]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])